[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium"]

[phases.install]
cmds = [
  "python3 -m venv /app/.venv",
  ". /app/.venv/bin/activate && pip install --upgrade pip",
  ". /app/.venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/app/.venv/bin/python bot.py"

